version: '3'

services:
  svc-greet:
    image: docker.io/mesameen/library-app:v1.0.0-dev
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 512M
